### ISSUE TITLE
endpoints require a object key in readme.md

### ISSUE THREAD

**Issue by WHK102** [martinheidegger/dns-query#1]
In documentation https://github.com/martinheidegger/dns-query#javascript-api says:

```
    /* Options (optional) */
    endpoints,
    retry: 3, // (optional) retries if a given endpoint fails; -1 = infinite retries; 0 = no retry
    timeout: 4000, // (optional, default=30000) timeout for single requests
    signal, // (optional) an AbortSignal to abort the request
  })
```

Replace by:

```
    /* Options (optional) */
    endpoints: endpoints,
    retry: 3, // (optional) retries if a given endpoint fails; -1 = infinite retries; 0 = no retry
    timeout: 4000, // (optional, default=30000) timeout for single requests
    signal, // (optional) an AbortSignal to abort the request
  })
```

`endpoints` need a object key.

**Comment by martinheidegger** [comment]
Thank you for the response @WHK102, the example is using [ES2015 shorthand notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015) for the endpoint documentation. It seemed simple enough for me. Do think the colon is necessary?

**Comment by WHK102** [comment]
For most people today I think yes, in a few more years no, but today yes because it causes confusion because the name of the variable is the same as the name of the property and this causes confusion.

Maybe I'm wrong and you're right, but not all of us know javascript in such a strict way.
